name: fl_charset
description: "Charset encoding and decoding Library, include ISO-(2-15), Windows Series, GBK, EUC-JP, EUC-KR, SHIFT-JIS, TCVN-3. And supported charset detect, canEncode, canDecode."
version: 1.0.1
homepage: "https://github.com/leanhtuan1994/fl_charset"
repository: "https://github.com/leanhtuan1994/fl_charset"

environment:
  sdk: '>=3.3.3 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


